version: '3.8'
services:
  app:
    image: my-buddy-backend
    pull_policy: always
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
        - /usr/src/app/.next
    ports:
      - "3001:3001"